### ISSUE TITLE
Property is being iterated even if it is removed from parent object

### ISSUE THREAD

**Issue by gpandurov** [couralex/deep-iterator#2]
I am using the default settings for iteration over an object and when certain conditions are met I am deleting part of the object but even when the property has been deleted it is still being processed in the next iterations. This is really nasty behaviour if your scenario is to update the tree while traversing it and is making the library unusable for such cases.

P.S. If there is workaround for this issue I would love to try it.

**Comment by couralex** [comment]
Hello, could you please write a minimal example of such behavior ? For example, the following code does take into account deleted properties : 
```
const obj = {a: 'a', b: 'b', c: 'c', d: 'd', e: 'e'};
let i = 0;
for (let {value} of deepIterator(obj)) {
  if (i++ === 2) {
    delete obj.d;
  }
  console.log(value);
}

// => displays obj(the root), then 'a', 'b', 'c', 'e'
```
If you use dfsPostOrder, the displayed root will also have the property deleted.
```
const obj = {a: 'a', b: 'b', c: 'c', d: 'd', e: 'e'};
let i = 0;
for (let {value} of deepIterator(obj, {search: 'dfsPostOrder'})) {
  if (i++ === 2) {
    delete obj.d;
  }
  console.log(value);
}

// => displays : 
a
b
c
e
{ a: 'a', b: 'b', c: 'c', e: 'e' }

```

**Comment by gpandurov** [comment]
Hi, here is a simple code sample.
```
const obj = { a: 1, b: [ 2, 3, { d: { x: '11' } } ], c: { p: 'a' } };

for (const currentEl of deepIterator(obj, { onlyLeaves: false })) {
    if (currentEl.done) {
        break;
    }

    if (currentEl.key === 'd') {
        currentEl.parent[currentEl.key] = {z : 12};
    }

    console.log('---------------------------------');
    console.log(currentEl.key, ' <-- key | value --> ', currentEl.value);
}
```
So what I am doing here is as follows: I am searching for object which key is 'd' and when I find it I change its value to { z: 12 }. After I change the value I would expect the next iteration to enter with the newly added object ie. { z: 12 }, but If you look at the console logs you can see that the code enters with { x: 11 } which was the old value.

**Comment by couralex** [comment]
In your example, the problem is that value {x: '11'} is already iterated before you replace it with another value in its parent. Deep-Iterator then recursively iterates through the already iterated value. That's an expected behavior.

Consider the following object to be iterated : 
const obj = {alpha: {beta: [1, 2, 3, 4, 5]}}

Suppose that, in the middle of the iteration of the beta array, you modify alpha and put a string instead. 
Should you stop the iteration of beta ? That's debatable but I expect implementations of deep iterators to continue the iteration. Any implementation that can handle this should have low performances (see the solution below).

Note that if you modify a value before it is iterated, there is no problem. In your example, if you replace :

```
if (currentEl.key === 'd') {
  currentEl.parent[currentEl.key] = {z : 12};
}
```

by 

```
if (currentEl.key === 'b') {
  currentEl.parent[currentEl.key][2]['d'] = {z : 12};
}
```

then {z: 12} is iterated.

As for a solution to your problem, you could check at each iteration if the yielded value is the same as the value you get from the root object (using node.path).

Here is an example of such implementation :

```
function* liveIterator(obj, options, removeRoot = false) {
  for (const node of deepIterator(obj, options)) {
    if (removeRoot && node.path.length === 0) {
      continue;
    }

    let modifiedParent = null;
    let parent = obj;
    let liveValue = obj;
    let key = undefined;

    for (key of node.path) {
      if (!(key in liveValue)) {
         modifiedParent = liveValue;
         break;
      }
      parent = liveValue;
      liveValue = liveValue[key]; 
    }

    if (modifiedParent === null) {
      if (liveValue !== node.value || key !== node.key) {
        modifiedParent = parent;
      }
    }

    if (modifiedParent !== null) {
      yield* liveIterator(modifiedParent, options, true);
    } else {
      yield node;
    }
  }
}

```
Now you can use liveIterator instead of deepIterator in your example : 
`for (const currentEl of liveIterator(obj, { onlyLeaves: false })) {`
and it works as you expected. It also works with the example I supplied with alpha and beta.
Note that it's a minimal implementation and may not work in every situations, but you can adapt the solution to your particular case. If you find a new corner case and can't find a workaround, feel free to provide another minimal example here.

**Comment by gpandurov** [comment]
I have already found a workaround for my case by reworking my code but I really appreciate the effort you put to provide me with solution to my problem and to give me a working example, keep up the good work.

Edit: Tested the provided solution - update the element one iteration earlier ie by using the parent of the parent to the element I want to replace and it works.

**Comment by gpandurov** [comment]
Workaround was provided for this issue as stated above.
